### ISSUE TITLE
Dev docs / docker env issue

### ISSUE THREAD

**Issue by metadave** [mozmeao/snippets-service#779]
I'm trying the docs for [Docker for development](https://github.com/mozmeao/snippets-service#docker-for-development) and am running into an issue:

```
ε !:! ~/moz/snippets-service $ docker-compose run web bash
Starting snippets-service_db_1 ... done
webdev@25578784d4f0:/app$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, base, contenttypes, product_details, reversion, sessions
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
webdev@25578784d4f0:/app$ python manage.py makemigrations
Migrations for 'product_details':
  /usr/local/lib/python3.7/site-packages/product_details/migrations/0003_auto_20181023_1934.py
    - Alter field last_modified on productdetailsfile
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/makemigrations.py", line 184, in handle
    self.write_migration_files(changes)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/makemigrations.py", line 223, in write_migration_files
    with open(writer.path, "w", encoding='utf-8') as fh:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/site-packages/product_details/migrations/0003_auto_20181023_1934.py'
webdev@25578784d4f0:/app$
```

**Comment by glogiotatidis** [comment]
Thanks for the bug report Dave. I'm not using docker for developer so obviously that's broken. I'll update the docs / dev procedure. 

Is there something blocking you atm?

**Comment by metadave** [comment]
thanks @glogiotatidis! I'm not blocked, but am looking to make it easier for other devs to onboard.

**Comment by jpetto** [comment]
FWIW, it would make for higher quality code review if I could run this locally. Currently, code review lacks functional/contextual/manual testing.

**Comment by glogiotatidis** [comment]
Thanks for bringing this into my attention folks. Will take care this week. I'll ping you both to review / test my changes if you have the time.

:eagle:

**Comment by jpetto** [comment]
Thank you!

**Comment by metadave** [comment]
@jpetto can you try out https://github.com/mozmeao/snippets-service/pull/827

I'm still getting the errors listed above. 

![about_docker_and_the_bouncing_souls_-_letter_from_iraq](https://user-images.githubusercontent.com/58244/48006649-e345ca80-e0e3-11e8-81a6-fb7d1413aaa4.png)

**Comment by glogiotatidis** [comment]
Dave reports that this is working for him.
